---
title: "Habitat *c*omplexity *r*educes feed*i*ng s*t*reng*t*h of fr*e*shwater p*r*edators (CRITTER) — Supplemental Statistics Report"
bibliography: references/CRITTERstatistics.bib
csl: "https://raw.githubusercontent.com/citation-style-language/styles/refs/heads/master/dependent/journal-of-animal-ecology.csl"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

This repository hosts the statistics report that is supplementing our [scientific preprint article](https://doi.org/10.1101/2025.02.22.639633) by @AranbarriEtAl2025ComplexityReducesFeeding investigating the effect of habitat complexity on the feeding functional response of two freshwater invertebrate predators. Find the full report as PDF [here](https://github.com/b-c-r/CRITTERstatistics/blob/main/statisticsReport.pdf). Find below information on related works and the location of the data and code.

## License

This report is published under the [**Creative Commons BY 4.0**](https://creativecommons.org/licenses/by/4.0/) license. The underlying code is licensed under the [**GNU General Public License 3**](https://www.gnu.org/licenses/gpl-3.0.html).

## How to cite this report

If you want to refer to our report, please cite:

Rall, B.C., Aranbarri, M., Flores, L., Guzmán, I. de, Larrañaga, A., & Reiss, J.(2025): Habitat complexity reduces the feeding strength of freshwater predators (CRITTER) — Supplemental Statistics Report. Zenodo. https://doi.org/10.5281/zenodo.14898819

Specific version(s):

Rall, B.C., Aranbarri, M., Flores, L., de Guzmán, I., Larrañaga, A., and Reiss, J. (2025): Habitat complexity reduces feeding strength of freshwater predators (CRITTER) — Supplemental Statistics Report (v0.1.2). Zenodo. https://doi.org/10.5281/zenodo.15348995

Rall, B.C., Aranbarri, M., Flores, L., de Guzmán, I., Larrañaga, A., and Reiss, J. (2025): Complexity reduces feeding strength of freshwater predators (CRITTER) - Supplemental Statistics Report (v0.1.1). Zenodo. https://doi.org/10.5281/zenodo.14907885

Rall, B.C., Aranbarri, M., Flores, L., de Guzmán, I., Larrañaga, A., and Reiss, J. (2025): Complexity reduces feeding strength of freshwater predators (CRITTER) - Supplemental Statistics Report (v0.1.0). Zenodo. https://doi.org/10.5281/zenodo.14898820


## Authors

-   Björn C. Rall ([0000-0002-3191-8389](https://orcid.org/0000-0002-3191-8389))
    -   [bjoern.rall@uni-konstanz.de](mailto:bjoern.rall@uni-konstanz.de)
    -   Aquatic Ecology and Evolution Group, Limnological Institute, University of Konstanz, Mainaustraße 252, 78464 Konstanz/Egg, Germany
-   Mireia Aranbarri ([0009-0001-3506-0914](https://orcid.org/0009-0001-3506-0914))
    -   [mireia.arambarri@ehu.eus](mailto:mireia.arambarri@ehu.eus)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
-   Lorea Flores ([0000-0002-0082-4072](https://orcid.org/0000-0002-0082-4072))
    -   [lflorescompains@gmail.com](mailto:lflorescompains@gmail.com)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
-   Ioar de Guzmán ([0000-0001-8894-8477](https://orcid.org/0000-0001-8894-8477))
    -   [mirenioar.deguzman@ehu.eus](mailto:mirenioar.deguzman@ehu.eus)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
    -   INRAE, UMR 1224, Ecologie Comportementale et Biologie des Populations de Poissons, Aquapôle, quartier Ibarron, 64310 Saint-Pée sur Nivelle, France.
-   Aitor Larrañaga ([0000-0002-0185-9154](https://orcid.org/0000-0002-0185-9154))
    -   [aitor.larranagaa@ehu.eus](mailto:aitor.larranagaa@ehu.eus)
    -   Laboratory of Stream Ecology, Department of Plant Biology and Ecology, Faculty of Science and Technology, University of the Basque Country, UPV/EHU PO Box 644, 48080 Bilbao, Spain
-   Julia Reiss ([0000-0002-3740-0046](https://orcid.org/0000-0002-3740-0046))
    -   [julia.reiss@brunel.ac.uk](mailto:julia.reiss@brunel.ac.uk)
    -   Centre for Pollution Research and Policy, Brunel University of London, Uxbridge, UB8 3PH, UK

## Related Works

-   [Data on Zenodo](https://doi.org/10.5281/zenodo.14891980) [@FloresEtAl2025ComplexityReducesFeedingData]

-   [Data on GitHub](https://github.com/b-c-r/CRITTERdata)

-   [R-Code on Zenodo](https://doi.org/10.5281/zenodo.14894598) [@RallEtAl2025ComplexityReducesFeedingCode]

-   [R-Code on GitHub](https://github.com/b-c-r/CRITTERcode)

-   [Supplemental Statistics Report on Zenodo](https://doi.org/10.5281/zenodo.14898819) [@RallEtAl2025ComplexityReducesFeedingStatistics]

-   [Supplemental Statistics Report on GitHub](https://github.com/b-c-r/CRITTERstatistics)

-   [Scientific Preprint Article](https://doi.org/10.1101/2025.02.22.639633) [@AranbarriEtAl2025ComplexityReducesFeeding]

## Code and Data

We wrote our report in R Markdown and bookdown. The R Markdown script imports the data and the required functions directly from our GitHub repositories [CRITTERdata](https://github.com/b-c-r/CRITTERdata) and [CRITTERcode](https://github.com/b-c-r/CRITTERcode), respectively [@FloresEtAl2025ComplexityReducesFeedingData;@RallEtAl2025ComplexityReducesFeedingCode]. You will find also an in-depth code description in the REAMDE of our [CRITTERcode](https://github.com/b-c-r/CRITTERcode) repository or in the [full statistical report](https://github.com/b-c-r/CRITTERstatistics/blob/main/statisticsReport.pdf). You will find laboratory methods in our [scientific preprint article](https://doi.org/10.1101/2025.02.22.639633) [@AranbarriEtAl2025ComplexityReducesFeeding].


## Required Packages

If you want to knit this report for yourself, you need to install:

- `bbmle` [@BolkerEtAl2023BbmleToolsGeneral]
- `bookdown` [@Xie2025BookdownAuthoringBooks]
- `doParallel` [@MicrosoftWeston2022DoParallelForeachParallel]
- `dplyr` [@WickhamEtAl2023DplyrGrammarData]
- `emdbook` [@Bolker2023EmdbookSupportFunctions]
- `foreach` [@MicrosoftWeston2022ForeachProvidesForeach]
- `frair` [@PritchardEtAl2017FrairToolsFunctional]
- `here` [@MullerBryan2020HereSimplerWay]
- `kableExtra` [@Zhu2024KableExtraConstructComplex]
- `knitr` [@Xie2024KnitrGeneralpurposePackage]
- `lhs` [@Carnell2024LhsLatinHypercubea]
- `MASS` [@RipleyEtAl2025MASSSupportFunctions]
- `odin` [@FitzJohn2024OdinODEGeneration]
- `png` [@Urbanek2022PngReadWrite]
- `purrr` [@WickhamHenry2025PurrrFunctionalProgramming]
- `RCurl` [@CRANTeamTempleLang2024RCurlGeneralNetwork]
- `sessioninfo` [@CsardiEtAl2025SessioninfoSessionInformation]
- `supportR` [@Lyon2024SupportRSupportFunctions]
- `tinytex` [@XiePositSoftwarePBC2025TinytexHelperFunctions]

We used TinyTex [@XiePositSoftwarePBC2025TinytexHelperFunctions] to create the pdf report. Please follow their installation guidelines using on [their homepage](https://yihui.org/tinytex/). You can, of course, use another LaTeX distribution, but we only tested if the RMarkdown script works using TinyTex.

**Please let us know if we forgot required packages.**


## Funding Information

-   Mireia Aranbarri was funded by the **Investigo Programm funded by the NextGenerationEU initiative**.
-   Lorea Flores was funded by a grant by the **Spanish Ministry of Education and Culture**.
-   Ioar de Guzmán was funded by the **Spanish Ministry of Science, Innovation and Universities (TED2021-129966B-C31)**.
-   Julia Reiss was supported by a **Royal Society of London Starting Grant**.
-   Björn C. Rall gratefully acknowledges the funding by the **German Science Foundation (DFG) to the Research Unit DynaSym (FOR 5064)**.

## References
